version: 0.0
os: linux
files:
  - source: gotinyurl.zip
    destination: /deploy/gotinyurl.zip
hooks:
  BeforeInstall:
    - location: scripts/install_n_start_docker.sh
    - location: Scripts/UnzipDataBundle.sh
  AfterInstall:
    - location: Scripts/RunResourceTests.sh
      timeout: 180
  ApplicationStart:
    - location: Scripts/RunFunctionalTests.sh
      timeout: 3600
  ValidateService:
    - location: Scripts/MonitorService.sh
      timeout: 3600
      runas: codedeployuser