version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/install_n_start_docker.sh
  AfterInstall:
    - location: scripts/stop_tinyurl_srv.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start_tinyurl_srv.sh
      timeout: 3600