version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.14
    commands:
      - env
      - go get -v -u golang.org/x/lint/golint

  build:
    commands:
      - echo Building the Go code...
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - export GOBIN=$GOPATH/bin
      - go get ./...
      - cd $CODEBUILD_SRC_DIR && golint -set_exit_status