version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.14
  build:
    commands:
      - echo Building the Go code...
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - ls -l