version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.14
    commands:
      - env
      - go get -v -u golang.org/x/lint/golint

  pre_build:
    commands:
      - echo Building the Go code...
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - export GOBIN=$GOPATH/bin
      - go get ./...
      - cd $CODEBUILD_SRC_DIR && golint -set_exit_status
  build:
    commands:
      - mkdir $CODEBUILD_SRC_DIR/build
      - cd $CODEBUILD_SRC_DIR
      - GOOS=linux  CGO_ENABLED=0 go build -o build/gourlshortner-linux
      - GOOS=darwin CGO_ENABLED=0 go build -o build/gourlshortner-darwin
      - GOOS=windows CGO_ENABLED=0 go build -o build/gourlshortner-win.exe
artifacts:
  files:
    - scripts/**
    - build/**
    - appspec.yml
    - urlshort.db
  name: go-tinyurl.zip
  discard-paths: yes